### PR TITLE
Add 2020 AL question

### PR DESCRIPTION
**Pull request by HasinduLanka**

### CODE REVIEW

**Comment by HasinduLanka** [comment]
Can someone add the 2021 question? I have to answer it next month 😕

**Comment by notnavindu** [comment]
@HasinduLanka Thank you for the contribution. Unfortunately I couldn't find the 2021 one. If you find it, please feel free to make a PR. If you don't know the answer, open an issue with the question.

**Comment by HasinduLanka** [comment]
> @HasinduLanka Thank you for the contribution. Unfortunately I couldn't find the 2021 one. If you find it, please feel free to make a PR. If you don't know the answer, open an issue with the question.

It was just a joke 😁 2021 A/Ls are due next month

**Comment by notnavindu** [comment]
lmho I completely forgot 😂

**Pull request merged**
